/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/clouds.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cloud.geometry}
        material={materials['water.cloud']}
        position={[2.819, 0, 0]}
        scale={1.233}
      />
    </group>
  );
}

useGLTF.preload('/models/clouds.glb');
