/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/experience-MID.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials.red}
        position={[0, 0, 0]}
        scale={6.5}
      />
    </group>
  );
}

useGLTF.preload('/models/experience-MID.glb');
