/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island-winter-house.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.574, 0]} scale={[0.576, 0.565, 0.576]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.house}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['white.ice']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseattic.geometry}
        material={materials.house}
        position={[0, 0.574, 0]}
        scale={[0.576, 0.565, 0.576]}
      />
      <group position={[0, 0.574, 0]} scale={[0.534, 0.565, 0.576]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.house}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials['white.ice']}
        />
      </group>
      <group position={[0, 0.701, 0]} scale={[0.576, 0.565, 0.576]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.house}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials['white.ice']}
        />
      </group>
      <group position={[-0.214, 1.392, 0.398]} scale={0.097}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials['white.ice']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.house}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[0.609, 0.368, -0.248]}
        scale={0.147}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mball007.geometry}
        material={materials['white.smoke']}
        position={[-0.307, 1.887, 0.457]}
        scale={0.105}
      />
    </group>
  );
}

useGLTF.preload('/models/island-winter-house.glb');
