/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island-fall.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Island.geometry}
        material={materials['yellow.land']}
        position={[-0.061, -0.04, 0.618]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.605}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.threetrunk.geometry}
        material={materials['three.brown']}
        position={[0.004, -0.152, 0.355]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials['tree.yellow']}
        position={[0.395, 1.263, 0.503]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.35, 0.237, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials['tree.orange']}
        position={[0.172, 1.571, 0.169]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.35, 0.237, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002.geometry}
        material={materials['tree.red']}
        position={[-0.193, 1.166, 0.533]}
        rotation={[1.504, 1.317, 0.312]}
        scale={[0.351, 0.238, 0.351]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere003.geometry}
        material={materials['tree.yellow']}
        position={[0.229, 1.029, -0.264]}
        rotation={[1.504, 1.317, 0.312]}
        scale={[0.351, 0.238, 0.351]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere004.geometry}
        material={materials['tree.red']}
        position={[-0.334, 1.282, 0.016]}
        rotation={[0.85, -0.359, -2.497]}
        scale={[0.351, 0.238, 0.351]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere005.geometry}
        material={materials['tree.yellow']}
        position={[0.513, 1.343, 0.107]}
        rotation={[0.85, -0.359, -2.497]}
        scale={[0.351, 0.238, 0.351]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere006.geometry}
        material={materials['tree.orange']}
        position={[0.126, 1.348, 0.811]}
        rotation={[0.85, -0.359, -2.497]}
        scale={[0.351, 0.238, 0.351]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere007.geometry}
        material={materials['tree.red']}
        position={[0.064, 1.661, 0.587]}
        rotation={[1.128, 0.127, -2.713]}
        scale={[0.248, 0.168, 0.248]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere008.geometry}
        material={materials['tree.yellow']}
        position={[-0.896, 1.11, 0.02]}
        rotation={[2.689, 0.572, 3.082]}
        scale={[0.232, 0.157, 0.232]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere009.geometry}
        material={materials['tree.orange']}
        position={[-0.749, 1.26, 0.016]}
        rotation={[-0.606, 1.111, 1.843]}
        scale={[0.232, 0.157, 0.232]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere010.geometry}
        material={materials['tree.red']}
        position={[-0.022, 1.025, -0.499]}
        rotation={[-0.606, 1.111, 1.843]}
        scale={[0.232, 0.157, 0.232]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere011.geometry}
        material={materials['tree.yellow']}
        position={[-0.177, 0.937, 0.754]}
        rotation={[-0.824, 1.144, 1.432]}
        scale={[0.232, 0.157, 0.232]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere012.geometry}
        material={materials['tree.red']}
        position={[0.005, 1.183, 1.187]}
        rotation={[-0.606, 1.111, 1.843]}
        scale={[0.232, 0.157, 0.232]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013.geometry}
        material={materials['tree.red']}
        position={[0.565, 0.997, 0.21]}
        rotation={[-0.606, 1.111, 1.843]}
        scale={[0.232, 0.157, 0.232]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014.geometry}
        material={materials['tree.yellow']}
        position={[-0.094, 1.608, 0.323]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere015.geometry}
        material={materials['tree.orange']}
        position={[0.669, 1.362, 0.646]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere016.geometry}
        material={materials['tree.yellow']}
        position={[-0.435, 1.496, -0.088]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere017.geometry}
        material={materials['tree.orange']}
        position={[-0.158, 1.081, -0.469]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere018.geometry}
        material={materials['tree.yellow']}
        position={[0.089, 1.184, 1.386]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[-0.294, -0.199, -0.294]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.roots.geometry}
        material={materials['three.brown']}
        position={[0.004, 0.52, 0.096]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.615}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere021.geometry}
        material={materials['rock.grey']}
        position={[0.401, 0.048, -0.151]}
        rotation={[3.018, -0.044, 1.268]}
        scale={0.219}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere022.geometry}
        material={materials['rock.grey']}
        position={[-0.057, 0.013, -0.275]}
        rotation={[2.743, 1.025, 1.372]}
        scale={0.191}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere023.geometry}
        material={materials['rock.grey']}
        position={[0.059, 0.041, 0.478]}
        rotation={[-1.612, -0.726, 1.364]}
        scale={0.144}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere024.geometry}
        material={materials['tree.orange']}
        position={[-0.35, -0.025, -0.565]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere025.geometry}
        material={materials['tree.red']}
        position={[-0.227, -0.038, 2.012]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere026.geometry}
        material={materials['tree.orange']}
        position={[0.753, 0.012, 0.486]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere027.geometry}
        material={materials['tree.orange']}
        position={[-1.44, -0.001, 0.5]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere028.geometry}
        material={materials['tree.red']}
        position={[1.239, -0.056, 1.351]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere029.geometry}
        material={materials['tree.red']}
        position={[0.344, 0.191, -0.173]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.root.geometry}
        material={materials['three.brown']}
        position={[-1.372, -0.145, 0.081]}
        rotation={[2.938, 0.565, -0.876]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere030.geometry}
        material={materials['rock.grey']}
        position={[-0.142, -0.049, 1.309]}
        rotation={[2.743, 1.025, 1.372]}
        scale={0.222}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere031.geometry}
        material={materials['rock.grey']}
        position={[-0.093, 0.127, 1.315]}
        rotation={[2.757, 1.031, 1.376]}
        scale={0.135}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere032.geometry}
        material={materials['tree.orange']}
        position={[-0.247, 0.012, 0.486]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere033.geometry}
        material={materials['tree.orange']}
        position={[-0.049, 0.225, 1.318]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.162, 0.11, 0.162]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere034.geometry}
        material={materials['tree.red']}
        position={[0.745, 1.257, 0.064]}
        rotation={[-2.49, Math.PI / 9, 2.081]}
        scale={[0.139, 0.094, 0.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere035.geometry}
        material={materials['tree.yellow']}
        position={[-0.168, 0.164, -0.27]}
        rotation={[-0.885, 1.13, 0.754]}
        scale={[0.08, 0.055, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere036.geometry}
        material={materials['tree.red']}
        position={[-0.313, 0.057, 0.042]}
        rotation={[0.308, 0.409, 1.25]}
        scale={[0.089, 0.06, 0.089]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pond.geometry}
        material={materials.water}
        position={[0.175, -0.047, 0.982]}
        scale={1.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pondfence.geometry}
        material={materials['three.brown']}
        position={[0.112, 0.081, 0.651]}
        rotation={[Math.PI / 2, 0, -0.542]}
        scale={[0.628, 1.071, 0.016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pondfencebars.geometry}
          material={materials['three.brown']}
          position={[0, -0.02, 1.694]}
          scale={[0.996, 1, 5.296]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/island-fall.glb');
