/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island-spring.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.portalring.geometry}
        material={materials['grey.portal.rock.002']}
        position={[-0.141, 0.288, 0]}
        scale={[3.592, 1.205, 1.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.portalfourtones.geometry}
        material={materials['grey.portal.rock.001']}
        position={[-0.087, 0.291, 0.006]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.382, 1.14, 0.382]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.portalring001.geometry}
        material={materials['portal.wirl']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree.geometry}
        material={materials['brown.tree.cherry']}
        position={[-0.115, -0.676, 0]}
        scale={[1.721, 1.189, 1.721]}
      >
        <group
          position={[-0.207, 1.122, -0.621]}
          rotation={[0.147, -0.458, 2.636]}
          scale={[0.199, 0.175, 0.177]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere020.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere020_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[-0.168, 2.125, 0.044]}
          rotation={[-0.536, -1.402, -0.546]}
          scale={[0.226, 0.244, 0.226]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere021.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere021_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[0.234, 0.894, 0.539]}
          rotation={[-1.204, -1.076, -1.153]}
          scale={[0.129, 0.133, 0.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere022.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere022_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[0.53, 1.676, -0.434]}
          rotation={[-1.4, -1.063, -1.095]}
          scale={[0.148, 0.147, 0.166]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere023.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere023_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[0.295, 1.538, -0.119]}
          rotation={[-1.4, -1.063, -1.095]}
          scale={[0.19, 0.189, 0.213]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere024.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere024_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[0.297, 1.236, -0.585]}
          rotation={[0, -1.539, 0.142]}
          scale={[0.148, 0.158, 0.147]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere026.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere026_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[0.175, 1.052, -0.541]}
          rotation={[0.748, -1.48, 1.054]}
          scale={[0.199, 0.202, 0.191]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere027.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere027_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[-0.257, 1.766, -0.499]}
          rotation={[-0.532, -0.056, 0.207]}
          scale={[0.23, 0.225, 0.254]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[-0.39, 1.406, 0.432]}
          rotation={[1.065, -0.345, 1.084]}
          scale={[0.202, 0.166, 0.256]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere028.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere028_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[0.315, 1.544, 0.475]}
          rotation={[0.144, -0.543, -0.952]}
          scale={[0.261, 0.165, 0.196]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere029.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere029_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[-0.646, 1.613, 0.067]}
          rotation={[1.065, -0.345, 1.084]}
          scale={[0.202, 0.166, 0.256]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere030.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere030_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group
          position={[-0.504, 1.484, -0.364]}
          rotation={[-0.177, -0.259, 0.739]}
          scale={[0.178, 0.133, 0.146]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere031.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere031_1.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group position={[0.044, 0.928, 0.625]} scale={[0.338, 0.489, 0.338]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere017_1.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere017_2.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
        <group position={[0.051, 1.182, 0.302]} scale={[0.338, 0.489, 0.338]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere018_1.geometry}
            material={materials['cherry.flower.pink01']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere018_2.geometry}
            material={materials['cherry.flower.pink02']}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base.geometry}
        material={materials.ground}
        position={[0.602, -0.045, 0.074]}
        scale={[1.615, 0.323, 1.615]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials['green.grass']}
          position={[0.37, 0.449, -0.716]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials['green.grass']}
          position={[-0.204, 0.44, -0.766]}
          rotation={[0, -0.955, 0]}
          scale={[0.04, 0.2, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials['green.grass']}
          position={[0.047, 0.422, 0.686]}
          scale={[0.04, 0.2, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials['green.grass']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone001.geometry}
          material={materials['grey.rock.001']}
          position={[0.1, 0.489, -0.647]}
          rotation={[0, 0.727, 0]}
          scale={[0.153, 0.766, 0.153]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone002.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone003.geometry}
          material={materials['grey.rock.001']}
          position={[-0.346, 0.243, 0.714]}
          scale={[0.064, 0.322, 0.064]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone004.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone005.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone006.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone007.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone008.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone010.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone011.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone012.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone013.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone014.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone015.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone016.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone017.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stone018.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stonelittle.geometry}
          material={materials['grey.rock.001']}
          position={[-0.017, 0.198, 0.548]}
          scale={[0.051, 0.256, 0.051]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stonelittle001.geometry}
          material={materials['grey.rock.001']}
          position={[-0.049, 0.294, 0.659]}
          rotation={[0, 0.874, 0]}
          scale={[0.042, 0.19, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stonelittle002.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stonelittle003.geometry}
          material={materials['grey.rock.001']}
          position={[0.3, 0.192, -0.68]}
          scale={[0.047, 0.237, 0.047]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stonelittle004.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stonelittle005.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground003.geometry}
          material={materials['brown.nase']}
          position={[0.929, -0.154, -0.478]}
          scale={0.697}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground004.geometry}
          material={materials['brown.nase']}
          rotation={[-Math.PI, 1.184, -Math.PI]}
          scale={0.697}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground005.geometry}
          material={materials['grey.rock.001']}
          position={[2.013, 2.391, -0.01]}
          scale={[0.2, 1, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground006.geometry}
          material={materials.ground}
          position={[0.929, -0.154, -0.478]}
          scale={0.697}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground007.geometry}
          material={materials.ground}
          rotation={[-Math.PI, 1.184, -Math.PI]}
          scale={0.697}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground01.geometry}
          material={materials['brown.nase']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.underground02.geometry}
          material={materials['brown.nase']}
          position={[0.076, -2.952, -0.124]}
          scale={0.697}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.portalpath.geometry}
        material={materials['grey.rock']}
        position={[0.412, -0.016, -0.094]}
        scale={[0.417, 0.849, 0.849]}
      />
      <group position={[1.28, 0.025, -0.55]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[1.11, -0.007, 0.851]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[0.804, 0.022, 0.954]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[1.887, 0.051, -0.102]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[0.679, 0.032, 1.643]}
        rotation={[-2.056, -0.372, 0.127]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[1.62, -0.015, 1.26]} rotation={[-2.159, -0.986, 0.654]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_2.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[2.555, -0.254, -0.388]}
        rotation={[-0.405, -0.794, -0.726]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[2.066, -0.224, -0.912]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-1.072, 0.009, -0.95]}
        rotation={[0.224, -0.647, 1.111]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-1.405, -0.057, 0.362]}
        rotation={[-2.253, -0.139, -1.381]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[-1.034, 0.216, 0.038]} rotation={[2.609, 0.419, 0.734]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.878, 0.689, 0.157]}
        rotation={[1.477, -0.506, 1.422]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.655, 0.708, 0.403]}
        rotation={[1.177, -0.828, 0.445]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.146, 0.211, 0.721]}
        rotation={[-1.998, 0.618, 0.458]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.844, -0.265, -1.407]}
        rotation={[-1.013, 0.103, 0.351]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.255, 0.782, -0.166]}
        rotation={[-0.219, 0.045, -0.402]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.186, 0.826, 0.119]}
        rotation={[-0.201, 0.031, -0.913]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.145, 0.602, 0.409]}
        rotation={[0.082, -0.583, -1.376]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[-0.448, 0.561, -0.565]}
        rotation={[-0.901, 0.501, -0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[-0.767, 0.846, -0.1]} rotation={[-0.988, 0.5, 0.189]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group
        position={[0.789, 0.243, -0.908]}
        rotation={[-3.122, 0.222, -0.026]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[0.373, 0.045, 0.214]} rotation={[0.019, 0, -0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
      <group position={[0.537, 0.041, -0.113]} rotation={[3.132, 0, -0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={materials['cherry.flower.pink01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_1.geometry}
          material={materials['cherry.flower.pink02']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/island-spring.glb');
