/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island-summer-isolate.glb');
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.045, 0, 0.288]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={3.636}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.mountain}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.rock}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.lava}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials['lava.black']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials.beach}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5.geometry}
          material={materials.water}
        />
      </group>
      <group
        position={[1.352, 0.615, 0.862]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.576, 1, 2.576]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[1.681, 0.56, 0.335]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[1.244, 0.515, -1.234]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.176, 0.452, -1.862]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.567, 0.772, -1.506]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.498, 1.557, -0.737]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.123, 1.618, -0.84]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-1.39, 0.706, -0.332]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-1.554, 0.757, 0.864]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-1.471, 0.867, 1.408]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.652, 1.274, 1.588]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.442, 1.193, 1.941]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.811, 0.915, 2.324]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-0.063, 1.079, 2.164]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.444, 1.326, 0.665]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.297, 1.499, 0.009]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.359, 1.643, -0.534]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.823, 1.261, -0.21]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.746, 1.318, -0.847]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[1.275, 0.225, -1.532]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[2.216, 0.86, 2.216]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_1.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/island-summer-isolate.glb');
