const skillNames = [
  { name: 'four star', score: 100 },
  { name: 'AWS', score: 60 },
  { name: 'Blender', score: 60 },
  { name: 'Datadog', score: 65 },
  { name: 'Django', score: 75 },
  { name: 'Docker', score: 35 },
  { name: 'Figma', score: 40 },
  { name: 'Firebase', score: 45 },
  { name: 'GCP', score: 60 },
  { name: 'Github', score: 75 },
  { name: 'Golang', score: 50 },
  { name: 'GraphQL', score: 70 },
  { name: 'Java', score: 50 },
  { name: 'JavaScript', score: 85 },
  { name: 'Jupyter Notebooks', score: 75 },
  { name: 'Linux', score: 45 },
  { name: 'MongoDB', score: 50 },
  { name: 'MySQL', score: 75 },
  { name: 'NextJS', score: 75 },
  { name: 'NodeJS', score: 80 },
  { name: 'PostgreSQL', score: 75 },
  { name: 'Python', score: 90 },
  { name: 'Pytorch', score: 50 },
  { name: 'React', score: 90 },
  { name: 'Redis', score: 50 },
  { name: 'Redux', score: 80 },
  { name: 'Scikit-Learn', score: 45 },
  { name: 'Tableau', score: 45 },
  { name: 'Tailwind', score: 60 },
  { name: 'TensorFlow', score: 50 },
  { name: 'ThreeJS', score: 50 },
  { name: 'TypeScript', score: 75 },
  { name: 'Vue', score: 80 },
];

const skills = skillNames.map(({ name, score }) => ({
  name,
  score,
  iconURL: `src/assets/images/icons/${name}.svg`,
}));

export { skills };
