/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/goku-cloud.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cloud.geometry}
        material={materials['yellow.cloud']}
        scale={[1.158, 0.798, 1.125]}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/goku-cloud.glb');
