/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/island-spring-portal-ring.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.portalringwater.geometry}
        material={materials['portal.wirl.001']}
        position={[-0.14, 0.289, -0.001]}
      />
    </group>
  );
}

useGLTF.preload('/models/island-spring-portal-ring.glb');
