/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF(
    '/models/island-winter-house-pillar.glb'
  );
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.272, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={materials['red.candy']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_1.geometry}
          material={materials['green.candy']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_2.geometry}
          material={materials['blue.candy']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_3.geometry}
          material={materials['yellow.candy']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/island-winter-house-pillar.glb');
